### ISSUE TITLE
Somfy Connexoon IO ook mogelijk

### ISSUE THREAD

**Issue by jeepke** [totalimmersion/com.somfy.tahoma#13]
Hallo,

Ik wilde graag mijn Somfy IO screens bedienen via de Homey en heb Uw app gedownload.
Echter werkt dit alleen met tussenkomst van de Somfy Tahoma box.

Nu heeft Somfy de goedkopere Connexoon IO op de markt gebracht. Eigenlijk een mini-Tahoma,
maar precies genoeg voor mij om de screens te kunnen bedienen.
Werkt Uw Somfy/homey app ook met deze mini-Tahoma ??  (deze module kost €139,00 ipv €300,00)

Alvast bedankt voor Uw antwoord.

**Comment by totalimmersion** [comment]
Beste,

Helaas werkt deze app niet met de Connexoon, omdat deze een andere API heeft als de Tahoma. Somfy is niet erg behulpzaam om hun platform voor derden open te stellen. Ik heb daarom ook alleen maar deze Tahoma app kunnen maken omdat ik deze zelf bezit en dus zodoende achter de API interace kon komen. De Connexoon bezit ik niet, waardoor ik hiermee niet kan helpen. Succes met de zoektocht.
