### ISSUE TITLE
App crashes on startup

### ISSUE THREAD

**Issue by Lusch81** [totalimmersion/com.somfy.tahoma#15]
This happens since update to 1.3.5.

Reboot of Homey nor reinstall of the app makes a difference.

**Comment by PeterEIER** [comment]
Hi Lennart, installed your v1.3.6 from GitHub via the CLI and this fixed the crash issue for me. Rgds, Peter.

**Comment by Lusch81** [comment]
Yes that worked for me too, thanks!
