### ISSUE TITLE
Thermis - temperature reading -250 degC

### ISSUE THREAD

**Issue by PeterEIER** [totalimmersion/com.somfy.tahoma#16]
After Somfy Tahoma updated the box my Thermis sensor shows 250degC or so in the Homey app, Tahoma app/box show normal temperature reading of around 25degC.

Issue is related to Kelvin <> degC.

![screen shot 2018-05-26 at 13 25 06](https://user-images.githubusercontent.com/25422313/40575608-3c202578-60e8-11e8-91e3-08a0b837bfaf.png)

the fix...
![screen shot 2018-05-26 at 13 25 58](https://user-images.githubusercontent.com/25422313/40575613-5a1bdfa4-60e8-11e8-8d70-a886fdc28680.png)

**Comment by totalimmersion** [comment]
Hoi Peter,

Dank dat je dit onder de aandacht brengt en tegelijk ook met de oplossing komt. Super ;-)
Ik ga het even aanpassen. Aangezien ik zelf niet de Thermis heb, zou jij eens in de Tahoma response kunnen kijken wat er precies door Tahoma terug gestuurd wordt? Ik denk nl. dat zij hun response hebben aangepast en in plaats van een temperatuur in Kelvin nu een temperatuur in Celcius terug sturen. Dat zou het verklaren, aangezien er op dit punt in mijn app geen veranderingen zijn geweest.

Groet,

Lennart

**Comment by PeterEIER** [comment]
Hoi Lennart,

attached is wat je zoekt? Of heb je nog meer nodig?

mvg,
Peter

[thermis-29mei2018.txt](https://github.com/totalimmersion/com.somfy.tahoma/files/2049729/thermis-29mei2018.txt)

**Comment by totalimmersion** [comment]
Hoi Peter,

Dank je. Dat was inderdaad wat ik nodig had. Mijn vermoeden is bevestigd. Somfy heeft de output aangepast en de temperatuur wordt nu in graden Celcius weergegeven i.p.v. (zoals eerder) Kelvin.
Ik heb de app aangepast. Zou jij de develop branch even willen testen?

Groet,

Lennart

**Comment by PeterEIER** [comment]
V1.3.7 geïnstalleerd vanuit de development branch.

Thermis en Sunis werken naar behoren, zo ook de scenario's die ik vanuit een flow activeer. Ik zeg problem fixed ;-) Bedankt.

**Comment by totalimmersion** [comment]
Hoi Peter, V1.3.7 is zojuist goedgekeurd door Athom en staat in de appstore.

**Comment by PeterEIER** [comment]
bedankt Lennart, geïnstalleerd vanuit de app store werkt als een zonnetje!
