### ISSUE TITLE
Feature request: support for the Somfy Thermis io sensor

### ISSUE THREAD

**Issue by PeterEIER** [totalimmersion/com.somfy.tahoma#2]
Would be great if besides the Sunis also the Thermis io sensor would be supported.

**Comment by totalimmersion** [comment]
Hi Peter, I would love to support the Thermis sensor, but I need some input from you in order to make this work.

I've created a pdf document with some instructions to get the information that I need. Would you be so kind to follow the instructions and provide me the necessary information?

Thanks in advance and if you have any questions please don't hesitate to ask.

[Instructions for the Thermis IO Sensor.pdf](https://github.com/totalimmersion/com.somfy.tahoma/files/1224825/Instructions.for.the.Thermis.IO.Sensor.pdf)

**Comment by PeterEIER** [comment]
Hi Lennart,

followed your instructions, attached the results....

Regards,
Peter

[thermis - step 11.pdf](https://github.com/totalimmersion/com.somfy.tahoma/files/1225894/thermis.-.step.11.pdf)
[thermis - step 9.txt](https://github.com/totalimmersion/com.somfy.tahoma/files/1225895/thermis.-.step.9.txt)
[thermis -step 14.txt](https://github.com/totalimmersion/com.somfy.tahoma/files/1225893/thermis.-step.14.txt)

**Comment by totalimmersion** [comment]
Hi Peter,

Thanks a lot, with this information I should be able to integrate the Thermis into the app. I'll get back to you as soon as I've something ready.

Best,

Lennart

**Comment by PeterEIER** [comment]
great, when you pull it off I'll buy you another cup of coffee ;-)

**Comment by totalimmersion** [comment]
Hi Peter,

Thanks for the coffee, I just saw it on Paypal. ;-)
I think I've managed to create a driver for the Thermis. Could you install the development branch (https://github.com/totalimmersion/com.somfy.tahoma/tree/develop/) on your Homey and test it?
You should be able to add the Thermis to Homey, have the temperature data available in the insights and use temperature changes as triggers and conditions in flows. Thanks in advance and please let me know if there are any issues, bugs, etc.

Best,

Lennart

**Comment by PeterEIER** [comment]
First tests are looking very promising!

![screen shot 2017-08-17 at 20 36 06](https://user-images.githubusercontent.com/25422313/29428005-f1a18800-838b-11e7-9998-9e813569eb16.png)

Build a flow sending the Temp value to MQTT, perfect. Can choose from 4 triggers etc.

**Comment by PeterEIER** [comment]
Lennart I found a bug... 

My Sunis did not show any data while the Thermis did, so I did some digging in the code, placed some traces etc... What I found was that the device url of the Thermis was also used for the Sunis... in your code there is a variable called sensor... it is used both for the Thermis as well as the Sunis. I renamed one of those variables to sensor1 and the Thermis and the Sunis are working as it should.

Take a look at my screenshot, it is self explaining I guess.

![bug report](https://user-images.githubusercontent.com/25422313/29473813-7cba19ca-8459-11e7-97e3-0941488e3357.png)

**Comment by PeterEIER** [comment]
@totalimmersion this one can do no harm ;-) The other screenshot shows the device urls etc.

![screen shot 2017-08-18 at 21 28 29](https://user-images.githubusercontent.com/25422313/29474530-625d4504-845c-11e7-9468-869d95783be9.png)

**Comment by totalimmersion** [comment]
Hi Peter,

I've changed the names of the variables. Could you test it again?

Best,

Lennart

**Comment by PeterEIER** [comment]
Hi Lennart,

Sure, installed the new version. I will give you an update tomorrow as values must change to update... Sunis will update at sunrise again.

Kind regards,
Peter
_____________________________

**Comment by PeterEIER** [comment]
You broke both sensors unfortunately :-(

You missed updating one of the variables... see screenshot, on the left the new code, on the right side my temporary fix, at the top in the orange box the adapted new code...

![failure](https://user-images.githubusercontent.com/25422313/29603555-e3532c56-87e4-11e7-9535-b1086db69354.png)

**Comment by totalimmersion** [comment]
Ah, stupid mistake. I've fixed it now, hopefully everything works as expected now.

**Comment by PeterEIER** [comment]
no problem Lennart, its working fine now. As soon as you release it I will buy you again a cup of coffee you deserve it ;-)

[Image]

Regards,
Peter
_____________________________

**Comment by totalimmersion** [comment]
Hi Peter,

Thanks a lot, much appreciated. ;-) Good to hear it's working fine now. I'll submit the app for review today.

Best Lennart

**Comment by PeterEIER** [comment]
Is Athom also reviewing apps like Apple does then?

**Comment by totalimmersion** [comment]
Yes they are, but they are not as stringent as Apple. ;-) I think Athom only checks the app to make sure it doesn't break there system.

**Comment by PeterEIER** [comment]
Okay, that is a good practice! Stability is of key importance... at least for me.

A few screenshots of the new Thermis functionality.

![file](https://user-images.githubusercontent.com/25422313/29659980-3def82a0-88c0-11e7-91de-22e7c4236d69.png)

![screen shot 2017-08-24 at 11 35 32](https://user-images.githubusercontent.com/25422313/29660462-b26931d4-88c1-11e7-9cf7-3a2c1783f5e9.png)

**Comment by PeterEIER** [comment]
![screen shot 2017-08-24 at 13 17 41](https://user-images.githubusercontent.com/25422313/29664139-c70e66ec-88ce-11e7-9e99-17cd0420f94e.png)

![screen shot 2017-08-24 at 13 17 59](https://user-images.githubusercontent.com/25422313/29664148-cc8c585e-88ce-11e7-8754-3ada588af34f.png)

![screen shot 2017-08-24 at 13 18 07](https://user-images.githubusercontent.com/25422313/29664154-cfb5c254-88ce-11e7-883c-098b7313f746.png)

![screen shot 2017-08-24 at 13 18 14](https://user-images.githubusercontent.com/25422313/29664168-d802a832-88ce-11e7-9386-2290c34c49fa.png)

**Comment by totalimmersion** [comment]
Hi Peter, the app is approved. I suspect it will be updated on your Homey in a couple of hours.
Thanks for your cooperation, couldn't have done it without you.
I'll have a look at the other feature request in a couple of days, so stay tuned. ;-)
Best,

Lennart

**Comment by PeterEIER** [comment]
Hi Lennart,

 

Great, will install the official release tomorrow. Thanks for adding this feature to your app! And as promised, enjoy your venti cappuccino ;-)

 

If I can help in testing the other feathers requests let me know. For myself this are however low prio features but I guess they are of great value to the app and its users.

 

Kind regards,

Peter

**Comment by totalimmersion** [comment]
Thanks a lot for the huge cappuccino, much appreciated!

**Comment by PeterEIER** [comment]
Hi Lennart,

 

Mijn Thermis is van slag… heb em al verwijderd en opnieuw toegevoegd… maar hij bijlft volhouden dat de buiten temp -246.25 C is… kijk ik via Tahoma dat is het 26.9 C…. volgens mij gaat er iets mis met de kelvin <> degC omrekening.

 

273.15 – 246.25 = 16,91 C

 

 

 

Met vriendelijke groet,

Peter

Sent from my iMac

 

From: Peter Eier <email4.einstein@gmail.com>
Date: Thursday, 24 August 2017 at 23:06
To: "totalimmersion/com.somfy.tahoma" <reply@reply.github.com>, "totalimmersion/com.somfy.tahoma" <com.somfy.tahoma@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: Re: [totalimmersion/com.somfy.tahoma] Feature request: support for the Somfy Thermis io sensor (#2)

 

Hi Lennart,

 

Great, will install the official release tomorrow. Thanks for adding this feature to your app! And as promised, enjoy your venti cappuccino ;-)

 

If I can help in testing the other feathers requests let me know. For myself this are however low prio features but I guess they are of great value to the app and its users.

 

Kind regards,

Peter

**Comment by PeterEIER** [comment]
Toevoeging…. 

 

Ik heb in jouw app de kelvin offset op nul gezet en dan heb ik weer juiste temperatuur 27,2 inmiddels.

 

 

Ps. Afgelopen dinsdag heeft Somfy de Tahoma box van nieuwe software voorzien… wellicht heeft Somfy iets gewijzigd waar jouw app nu last van heeft. 

 

Met vriendelijke groet,

Peter

Sent from my iMac

 

From: Peter Eier <email4.einstein@gmail.com>
Date: Saturday, 26 May 2018 at 13:10
To: "totalimmersion/com.somfy.tahoma" <reply@reply.github.com>, "totalimmersion/com.somfy.tahoma" <com.somfy.tahoma@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: Re: [totalimmersion/com.somfy.tahoma] Feature request: support for the Somfy Thermis io sensor (#2)

 

Hi Lennart,

 

Mijn Thermis is van slag… heb em al verwijderd en opnieuw toegevoegd… maar hij bijlft volhouden dat de buiten temp -246.25 C is… kijk ik via Tahoma dat is het 26.9 C…. volgens mij gaat er iets mis met de kelvin <> degC omrekening.

 

273.15 – 246.25 = 16,91 C

 

 

 

Met vriendelijke groet,

Peter

Sent from my iMac

 

From: Peter Eier <email4.einstein@gmail.com>
Date: Thursday, 24 August 2017 at 23:06
To: "totalimmersion/com.somfy.tahoma" <reply@reply.github.com>, "totalimmersion/com.somfy.tahoma" <com.somfy.tahoma@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: Re: [totalimmersion/com.somfy.tahoma] Feature request: support for the Somfy Thermis io sensor (#2)

 

Hi Lennart,

 

Great, will install the official release tomorrow. Thanks for adding this feature to your app! And as promised, enjoy your venti cappuccino ;-)

 

If I can help in testing the other feathers requests let me know. For myself this are however low prio features but I guess they are of great value to the app and its users.

 

Kind regards,

Peter
