### ISSUE TITLE
scherm open

### ISSUE THREAD

**Issue by jmoorman777** [totalimmersion/com.somfy.tahoma#21]
Goedemorgen - 

is het ook mogelijk om een scherm open te zetten ( bijv uitvalscherm in de tuin ) - op een bepaalde setting  ? - 
ik had in mijn tahomabox bijv scherm open 40 %  - scherm open 60 % - naarmate er meer licht buiten was liet ik het scherm meer of minder open gaan - zo wordt het binnen niet te donker - 

maar een idee hoor :)

groeten
jan

**Comment by totalimmersion** [comment]
Vanaf versie 1.5.0 is het mogelijk om een specifieke positie toe te voegen. Wel moeten de betreffende apparaten even verwijderd en opnieuw toegevoegd worden.
