### ISSUE TITLE
zonnewering gaat verkeerde kant op

### ISSUE THREAD

**Issue by hplos** [totalimmersion/com.somfy.tahoma#22]
Hoi,

Vannacht werd ik wakker van mijn zonnewering. Ik had een flow gemaakt, dat wanneer het ging regenen, dat mijn zonnescherm omhoog moet gaan.

Blijkbaar gaat ie dan juist helemaal uit, inplaats van in. Bij mijn rolluiken werkt het wel naar behoren :)

**Comment by totalimmersion** [comment]
Hoi, wat voor zonwering heb je? Bij mijn eigen zonwering gaat het namelijk wel goed.

**Comment by hplos** [comment]
Hoi Lennart,

Ik heb zonneweringen met Somfy IO motoren. De rolluiken gaan goed, maar het zonnescherm lijkt net verkeerd om te gaan.

Wanneer ik ‘m wil bedienen via de knoppen in de homey app werkt het volgens mij wel zoals je verwacht. Dit zal ik vanavond nog even checken :)

Omdat het IO motoren zijn verloopt de communicatie via een Tahoma box.

**Comment by totalimmersion** [comment]
Ok, ik ben benieuwd naar je bevindingen. Tevens zou ik graag willen weten wat voor een soort zonwering het is. Zijn het bijv. verticale screens of een horizontaal scherm?

**Comment by hplos** [comment]
Het is een horizontaal scherm

Deze, hij staat op de foto een klein stukje uit. Nogmaals: de rolluiken
(verticaal dus) werken wel naar behoren
Wel moet ik altijd eerst een keer een stop commando sturen en vervolgens
kan ik pas kiezen naar boven of naar beneden.

On de bijlage staat een screenshot van de app waarin ik de rolluiken altijd
vindt.







On 16 Jan 2019, at 16:17, Lennart <notifications@github.com> wrote:

Ok, ik ben benieuwd naar je bevindingen. Tevens zou ik graag willen weten
wat voor een soort zonwering het is. Zijn het bijv. verticale screens of
een horizontaal scherm?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/totalimmersion/com.somfy.tahoma/issues/22#issuecomment-454816074>,
or mute the thread

**Comment by hplos** [comment]
Goedenavond

Met de knop die nu ingedrukt is, gaat het scherm in.

Ik zou net andersom verwachten. Wat ik vanmiddag zei klopt dus niet.
Ik denk dat het in en uitrollen net andersom moet.
Vraag is allen is dat bij alle horizontale zonneschermen zo of is dat bij
alle IO motoren of ook dat niet...


Op wo 16 jan. 2019 om 16:22 schreef Hans-Peter Los <hanspeterlos@gmail.com>

> Het is een horizontaal scherm
>
> Deze, hij staat op de foto een klein stukje uit. Nogmaals: de rolluiken
> (verticaal dus) werken wel naar behoren
> Wel moet ik altijd eerst een keer een stop commando sturen en vervolgens
> kan ik pas kiezen naar boven of naar beneden.
>
> On de bijlage staat een screenshot van de app waarin ik de rolluiken
> altijd vindt.
>
>
>
>
>
>
>

**Comment by totalimmersion** [comment]
Bij de verticale zonneschermen is `open` naar boven en `closed` naar beneden. Ik heb het vermoeden dat bij horizontale schermen dat `open` betekent dat het scherm naar buiten staat en bij `closed` naar binnen (precies andersom dus). Ik heb nu een update uitgebracht (versie 1.5.1), waarbij ik dit voor de horizontale schermen omgedraaid heb. Hopelijk is met deze update het probleem verholpen. Aangezien ik zelf geen horizontale schermen heb, kan ik het zelf niet testen. Ik hoor graag of het nu naar behoren werkt.

**Comment by hplos** [comment]
Hoi Lennart,

Ik zal de app binnenkort updaten en daarna zal ik je laten weten of het ok
werkt.

Vriendelijke groet,
Hans-Peter Los

Op ma 21 jan. 2019 om 16:48 schreef Lennart <notifications@github.com>

**Comment by totalimmersion** [comment]
Ik ga er vanuit dat dit issue is opgelost, daarom sluit ik dit issue.

**Comment by hplos** [comment]
Ohja!
Ik zal morgen even kijken of ik tijd heb om te kijken of dit werkelijk het
geval is :)

Is de API van de tahoma box (of API van somfy waar je tegenaanpraat)
publiekelijk?

Ben benieuwd of het ook mogelijk is om hetzelfde te doen als je ook met een
afstandsbediening kan doen met de ‘my’ knop. Dan gaan onze rolluiken op
ventilatiestand.

Wellicht kan ik helpen bij de ontwikkeling daarvan.

Graag hoor ik van je of die API publiekelijk is of hoe jij aan je info komt
:)

Vriendelijke groet,
Hans-Peter Los

Op do 14 feb. 2019 om 20:42 schreef Lennart <notifications@github.com>

**Comment by totalimmersion** [comment]
Hoi Hans-Peter,
Somfy is sinds kort wel bezig met een publieke API, maar helaas zijn de functies daarvan nog te beperkt om daar gebruik van te maken. Wat ik dus gedaan heb is in de browers gekeken welke requests de browser naar de Tahoma server verstuurd. Op deze wijze heb ik al mijn commando's weten te achterhalen en dat heb ik in de Homey app gebruikt. Voor zover ik weet zit de 'my' knop enkel op de afstandsbediening en niet in de tahoma app / website, ik ben dan ook bang dat dat niet vanuit Homey te ondersteunen is.

Groet,

Lennart

**Comment by hplos** [comment]
Ah ok,

Bedankt voor je antwoord!
Ik zal vandaag de app updaten om even te kijken of je aanpassing werkt.

Groetjes!

**Comment by hplos** [comment]
Werkt! Bedankt voor het aanpassen :)
