### ISSUE TITLE
VELUX IO exterior roller shutters

### ISSUE THREAD

**Issue by roody1997** [totalimmersion/com.somfy.tahoma#23]
zou je VELUX IO exterior roller shutters kunnen toe voegen aan de Homey-somfy.tahoma app

**Comment by totalimmersion** [comment]
Hoi,

Dat wil ik wel, maar om dat te doen heb ik iets meer informatie nodig. Ik heb een pdf bijgevoegd met een aantal instructies, als je mij die informatie wilt sturen dan kan ik het betreffende apparaat toevoegen.

Groet,

Lennart

[Instructions for the TaHoma devices.pdf](https://github.com/totalimmersion/com.somfy.tahoma/files/2509351/Instructions.for.the.TaHoma.devices.pdf)

**Comment by roody1997** [comment]
dit zou het moeten zijn denk ik.

nog een kleine opmerking, de standaard knop voor het velux raam heb je
genaamd boven / beneden ipv open / dicht, wat iets duidelijker is, ik wet
alleen niet of dat dat in alle gevallen zo is,

Dat de koffie mag smaken XD

Roody

Op wo 24 okt. 2018 om 09:12 schreef Lennart <notifications@github.com>:

**Comment by roody1997** [comment]
mocht het e.e.a. niet mee gekomen zijn

 "creationTime":1540030131000,
         "lastUpdateTime":1540030131000,
         "label":"Zolder RL 3",
         "deviceURL":"geheime info ?",
         "shortcut":false,
         "controllableName":"io:RollerShutterVeluxIOComponent",
         "definition":{  
            "commands":[  
               {  
                  "commandName":"close",
                  "nparams":0
               },
               {  
                  "commandName":"delayedStopIdentify",
                  "nparams":1
               },
               {  
                  "commandName":"down",
                  "nparams":0
               },
               {  
                  "commandName":"getName",
                  "nparams":0
               },
               {  
                  "commandName":"identify",
                  "nparams":0
               },
               {  
                  "commandName":"my",
                  "nparams":0
               },
               {  
                  "commandName":"open",
                  "nparams":0
               },
               {  
                  "commandName":"refreshMemorized1Position",
                  "nparams":0
               },
               {  
                  "commandName":"setClosure",
                  "nparams":1
               },
               {  
                  "commandName":"setDeployment",
                  "nparams":1
               },
               {  
                  "commandName":"setMemorized1Position",
                  "nparams":1
               },
               {  
                  "commandName":"setName",
                  "nparams":1
               },
               {  
                  "commandName":"setPosition",
                  "nparams":1
               },
               {  
                  "commandName":"setSecuredPosition",
                  "nparams":1
               },
               {  
                  "commandName":"startIdentify",
                  "nparams":0
               },
               {  
                  "commandName":"stop",
                  "nparams":0
               },
               {  
                  "commandName":"stopIdentify",
                  "nparams":0
               },
               {  
                  "commandName":"up",
                  "nparams":0
               },
               {  
                  "commandName":"wink",
                  "nparams":1
               }
            ],
            "states":[  
               {  
                  "type":"ContinuousState",
                  "qualifiedName":"core:ClosureState"
               },
               {  
                  "type":"ContinuousState",
                  "qualifiedName":"core:Memorized1PositionState"
               },
               {  
                  "type":"DataState",
                  "qualifiedName":"core:NameState"
               },
               {  
                  "values":[  
                     "closed",
                     "open"
                  ],
                  "type":"DiscreteState",
                  "qualifiedName":"core:OpenClosedState"
               },
               {  
                  "type":"ContinuousState",
                  "qualifiedName":"core:PriorityLockTimerState"
               },
               {  
                  "type":"ContinuousState",
                  "qualifiedName":"core:RSSILevelState"
               },
               {  
                  "type":"ContinuousState",
                  "qualifiedName":"core:SecuredPositionState"
               },
               {  
                  "values":[  
                     "available",
                     "unavailable"
                  ],
                  "type":"DiscreteState",
                  "qualifiedName":"core:StatusState"
               },
               {  
                  "values":[  
                     "comfortLevel1",
                     "comfortLevel2",
                     "comfortLevel3",
                     "comfortLevel4",
                     "environmentProtection",
                     "humanProtection",
                     "userLevel1",
                     "userLevel2"
                  ],
                  "type":"DiscreteState",
                  "qualifiedName":"io:PriorityLockLevelState"
               },
               {  
                  "values":[  
                     "LSC",
                     "SAAC",
                     "SFC",
                     "UPS",
                     "externalGateway",
                     "localUser",
                     "myself",
                     "rain",
                     "security",
                     "temperature",
                     "timer",
                     "user",
                     "wind"
                  ],
                  "type":"DiscreteState",
                  "qualifiedName":"io:PriorityLockOriginatorState"
               }
            ],
            "dataProperties":[  
               {  
                  "value":"500",
                  "qualifiedName":"core:identifyInterval"
               }
            ],
            "widgetName":"PositionableTiltedRollerShutter",
            "uiClass":"RollerShutter",
            "qualifiedName":"io:RollerShutterVeluxIOComponent",
            "type":"ACTUATOR"
         },
         "states":[  
            {  
               "name":"core:NameState",
               "type":3,
               "value":"Zolder RL 3"
            },
            {  
               "name":"core:PriorityLockTimerState",
               "type":1,
               "value":0
            },
            {  
               "name":"core:StatusState",
               "type":3,
               "value":"available"
            },
            {  
               "name":"core:RSSILevelState",
               "type":2,
               "value":4.0
            },
            {  
               "name":"core:ClosureState",
               "type":1,
               "value":100
            },
            {  
               "name":"core:OpenClosedState",
               "type":3,
               "value":"closed"
            }
         ],
         "attributes":[  

         ],
         "available":true,
         "enabled":true,
         "placeOID":"geheime info ?",
         "widget":"PositionableTiltedRollerShutter",
         "type":1,
         "oid":"geheime info ?",
         "uiClass":"RollerShutter"
      },

**Comment by totalimmersion** [comment]
De Velux IO roller shutter is in versie 1.5.0 toegevoegd.
