### ISSUE TITLE
VELUX

### ISSUE THREAD

**Issue by roody1997** [totalimmersion/com.somfy.tahoma#24]
kan je de funktie uitbreiden met / naar een % opening zoals deze ook in de tahoma box zit, voor zowel de velux ramen, blinds als de evt exterior roller shutters.

Zodat als je 75% in geeft hij automatisch naar bijna dicht gaat, nu is het voledig aan of uit in de vorm van open of dicht, 

Gr Roody1997

**Comment by totalimmersion** [comment]
Hoi,

Dit is inderdaad iets wat ik op mijn todo lijstje heb staan. Zodra ik er tijd voor heb ga ik hier mee aan de slag.

Groet,

Lennart

**Comment by totalimmersion** [comment]
En ik zag dat je ook een donatie op Paypal hebt gedaan, waarvoor hartelijk dank ;)

Groet,

Lennart

**Comment by totalimmersion** [comment]
Vanaf versie 1.5.0 is het mogelijk om een exacte positie in te stellen (apparaten moet hiervoor wel even verwijderd en opnieuw toegevoegd worden aan Homey).
