### ISSUE TITLE
somfy GDK800 

### ISSUE THREAD

**Issue by joeyedelijn** [totalimmersion/com.somfy.tahoma#26]
Zou er ook ondersteuning kunnen komen voor de GDK800? Dit is een motor voor de garagedeur?

**Comment by totalimmersion** [comment]
Hoi Joey,

Volgens mij is de GDK800 een RTS apparaten. De tahoma app ondersteund geen RTS apparaten. Voor RTS apparaten moet de somfy RTS app gebruikt worden: https://apps.athom.com/app/com.somfy

Groet,

Lennart
