### ISSUE TITLE
vraag

### ISSUE THREAD

**Issue by Hans1965** [totalimmersion/com.somfy.tahoma#29]
Ha Lennart, ik ben een nieuweling. ik krijg mijn tahoma niet gekoppelt aan mijn homey. kan jij me helpen? vast hartelijk dank.

**Comment by totalimmersion** [comment]
Hoi Hans, kun je aangeven wat er niet lukt? Lukt het je bijvoorbeeld niet om in te loggen, of lukt het niet om bepaalde apparataten te koppelen in Homey?

Groet,

Lennart

**Comment by Hans1965** [comment]
Ha Lennart,

Bedankt voor je reactie, ik heb een zonnescherm en een rolluik Somfy io met een tahomabox. Ik heb de toegangscodes van de tahoma erin staan maar hij ziet geen apparaten. Dus ik denk dat er iets niet goed gaat...... ik neem aan dat ik de apparaten niet apart hoeft aan te melden.

Met vriendelijke groet,

Hans Luijk

**Comment by totalimmersion** [comment]
Hoi Hans,

Als je eenmaal met Homey ingelogd bent in Tahoma (in het instellingen
scherm), dan moet je daarna de betreffende zonneschermen en rolluiken nog
toevoegen aan de betreffende zones in Homey (druk op de grote + knop in de
betreffende zone, vervolgens klik je op 'Somfy Tahoma' in het popup scherm
dat tevoorschijn komt en daar klik je op het type apparaat (rolluik of
zonnescherm) dat je aan Homey wilt toevoegen).
Hiermee zou het moeten werken.

Groet,

Lennart

**Comment by Hans1965** [comment]
Ok, ik ga het uitproberen. Je hoort van mij. Bedankt!!

Met vriendelijke groet,

Hans Luijk

> Op 14 jan. 2019 om 15:33 heeft Lennart <notifications@github.com> het volgende geschreven:
> 
> Hoi Hans,
> 
> Als je eenmaal met Homey ingelogd bent in Tahoma (in het instellingen
> scherm), dan moet je daarna de betreffende zonneschermen en rolluiken nog
> toevoegen aan de betreffende zones in Homey (druk op de grote + knop in de
> betreffende zone, vervolgens klik je op 'Somfy Tahoma' in het popup scherm
> dat tevoorschijn komt en daar klik je op het type apparaat (rolluik of
> zonnescherm) dat je aan Homey wilt toevoegen).
> Hiermee zou het moeten werken.
> 
> Groet,
> 
> Lennart
>

**Comment by Hans1965** [comment]
Als ik dat doe geeft hij de melding: geen apparaten!!

Met vriendelijke groet,

Hans Luijk

> Op 14 jan. 2019 om 15:33 heeft Lennart <notifications@github.com> het volgende geschreven:
> 
> Hoi Hans,
> 
> Als je eenmaal met Homey ingelogd bent in Tahoma (in het instellingen
> scherm), dan moet je daarna de betreffende zonneschermen en rolluiken nog
> toevoegen aan de betreffende zones in Homey (druk op de grote + knop in de
> betreffende zone, vervolgens klik je op 'Somfy Tahoma' in het popup scherm
> dat tevoorschijn komt en daar klik je op het type apparaat (rolluik of
> zonnescherm) dat je aan Homey wilt toevoegen).
> Hiermee zou het moeten werken.
> 
> Groet,
> 
> Lennart
>

**Comment by totalimmersion** [comment]
In dat geval vermoed ik dat jouw apparaten nog niet ondersteund worden door de Homey app. Om jouw apparaten toe te kunnen voegen aan de app heb ik wat meer informatie nodig. Ik heb hiervoor een document opgesteld met een aantal stappen om de betreffende informatie op te zoeken. Als je mij die informatie kan aanleveren, dan kan ik kijken of ik jouw apparaten ook kan toevoegen.

Groet,

Lennart
[Instructions for the TaHoma devices.pdf](https://github.com/totalimmersion/com.somfy.tahoma/files/2755931/Instructions.for.the.TaHoma.devices.pdf)

**Comment by totalimmersion** [comment]
Hoi Hans,

Ik heb even gekeken, maar zowel de zonnesensor als het zonnescherm worden al ondersteund, deze moet je dus gewoon kunnen toevoegen. Ik heb zelf de zonnesensor ook en heb het zojuist nog even gechecked, maar dat werkt gewoon goed.
Jouw rolluik wordt nog niet ondersteund, maar zal ik toevoegen in een toekomstige versie.

Groet,

Lennart

**Comment by totalimmersion** [comment]
Goed om te horen dat het gelukt is. Dat de draairichting veranderd is, is iets dat ik nu van meerdere mensen heb gehoord. Ik ben bezig om dat probleem op te lossen. Dat zal in een volgende update zijn.

**Comment by Hans1965** [comment]
Bij sommige apparatuur zit op het scherm een schuifknop om de werking van de app om te draaien.

Met vriendelijke groet,

Hans Luijk

**Comment by totalimmersion** [comment]
Hoi Hans, ik heb een update uitgebracht (1.5.1) waarin ik jouw rolluik ondersteun. Tevens heb ik de draairichting van het scherm heb omgedraaid. Aangezien ik zelf dit type apparaten niet heb, kan ik het zelf niet testen. Mochten er nog problemen zijn dan hoor ik dat graag.

Groet,

Lennart

**Comment by Hans1965** [comment]
Dankjewel, je hoort van me!

Met vriendelijke groet,

Hans Luijk

**Comment by Hema40** [comment]
hoi Lennart,
Ik probeer mij probleem maar even hier uit te leggen want ik kom anders niet door het forum heen met een nieuw onderwerp

**Comment by Hema40** [comment]
Ik heb een probleem met het besturen van mij rolluiken het is namelijk zo,

Kan jij mij helpen met een probleem waar ik vanaf de laatste update van Tahoma tegen aan loop.
Ik zal het uitleggen na de update welke bijna gelijk liep aan de firmware update van mij Homey heb ik problemen met de aansturing van de rolluiken welke via de Tahoma box worden aangestuurd.
Ik heb alle apparaten in Homey verwijderd en opnieuw op Homey geïnstalleerd.
Het zag er direct een stuk beter uit en een aantal functionaliteiten had ik vervolgens weer terug. ziet er prima uit.
Echter er zit nog een probleempje in de aansturing waarvan ik het vermoeden heb dat het een bug is????
Ik kan namelijk de rolluiken voor een deel via een Flow's besturen.
Als ik de luiken door Homey laat sluiten gaat alles goed, echter als ik deze dan weer via een tweede Flow wil openen gaat het fout.
Het commando wordt niet opgevolgd. Ik vermoed dat het commando niet door Homey wordt gegeven.
Deze conclusie trek ik uit het feit dat als ik inlog op de Tahoma box ik namelijk zie dat de rolluiken de status gesloten hebben wat juist is en ik de luiken via de Tahoma box wel kan openen.
Daar zit dan ook het verschil als ik in de App de status check is het zo dat het rondje (wit gekleurd) met daarin de pijl getekend niet van status omhoog naar omlaag veranderd als de luiken gesloten zijn.
Wat wel veranderd is het zogenaamde raam wat van licht naar donker kleurt.
Homey ziet dus wel een status verandering maar de pijl welke naar mij idee moet zorgen voor het commando om te openen veranderd niet mee.
Als aanvulling wil ik nog meegeven dat als ik de pijl handmatig naar de status omlaag toe zet de rolluiken het commando openen wel overnemen.
Dat is niet echt handig om dit zelf elke dag op deze manier uit te voeren.
Ik zal voor de duidelijkheid een aantal screenshots bijvoegen en hopelijk kunt u mij snel van en oplossing voorzien.
Mochten er nog vragen of onduidelijkheden zijn dan hoor ik het graag.

Ik wil nog wel even meegeven dat ik tot op heden erg tevreden ben over de 2.0 versie.
Kan veel sneller wijzigingen of andere opties aanmaken, bijvoegen al moest ik heel even wennen aan het programmeren via de App.

**Comment by Hema40** [comment]
![tahoma versie](https://user-images.githubusercontent.com/47194535/52184370-ac7e6e00-2812-11e9-8ef0-24c90c956986.jpg)
![status gesloten beeld](https://user-images.githubusercontent.com/47194535/52184371-ac7e6e00-2812-11e9-9c2d-d09903d62280.jpg)
![status open beeld](https://user-images.githubusercontent.com/47194535/52184372-ad170480-2812-11e9-9bce-f103b1035559.jpg)
![status gesloten functie](https://user-images.githubusercontent.com/47194535/52184373-ad170480-2812-11e9-8f3d-5f6a82793050.jpg)
![status open functie](https://user-images.githubusercontent.com/47194535/52184374-ad170480-2812-11e9-9de9-4201e76ef28d.jpg)

**Comment by totalimmersion** [comment]
Ik ga er vanuit dat alles goed werkt, daarom sluit ik dit issue.

**Comment by Hema40** [comment]
Hoi Lennart ik zag gisteren nog niet goed werkte zal de app opnieuw installeren dan laat ik het weten
