### ISSUE TITLE
Tip: supporting even more devices by this simple trick...

### ISSUE THREAD

**Issue by PeterEIER** [totalimmersion/com.somfy.tahoma#3]
Installed your app as developer took a look at your exterior blind driver... found code: if (device.controllableName == 'io:VerticalExteriorAwningIOComponent') {  

Using the instruction from GitHub for the Thermis... found that "device controllable name" for shutters is... io:RollerShutterGenericIOComponent... 

When I change your code into if (device.controllableName == 'io:RollerShutterGenericIOComponent') { my shutters are found and can be fully controlled by Homey ;-)

Executed the same trick for Velux dakraam (io:WindowOpenerVeluxIOComponent) and Velux blinds ( io:VerticalInteriorBlindVeluxIOComponent)... both works like a charm.

**Comment by totalimmersion** [comment]
Hi Peter,

Once I have the Thermis in the app, I will have a look at these devices.

Best,

Lennart

**Comment by totalimmersion** [comment]
Hi Peter,

Now that the app is compatible is with SDK 2, I started to support the devices you mentioned above. Would you be so kind to test the latest version (1.3.0), which supports these devices? This version can be found on the development branch.
Thank you very much for your cooperation.

Best,

Lennart

**Comment by PeterEIER** [comment]
Sure, give me a couple of days to test.

**Comment by PeterEIER** [comment]
Adding the devices and their basic functionality tested and working fine.

![screen shot 2017-10-27 at 16 31 23](https://user-images.githubusercontent.com/25422313/32109358-cb42e7c2-bb34-11e7-8590-89aba480eea7.png)

![screen shot 2017-10-27 at 16 31 06](https://user-images.githubusercontent.com/25422313/32109372-d49bb092-bb34-11e7-8032-34b67d297b6f.png)

**Comment by PeterEIER** [comment]
Tahoma scenario was executed as programmed in Homey flow, "rolluiken" were closed.

Will test Velux "dakraam / zonwering" during the weekend.

**Comment by PeterEIER** [comment]
Version tested: 1.3.0

**Following tests performed on rolluik(io), Velux dakraam(io) and Velux zonwering(io):**
1a/ adding devices: passed.
1b/ adding multiple devices of the same type at once: passed.
2/ deleting devices: passed.
3/ adding after delete: passed.
4/ basic functions in the devices section of Homey, up/down/stop: passed.
5/ Triggering Tahoma scenarios in Homey flows: passed.
**Existing devices**
6/ Sunis still working: passed.
7/ Thermis still working: passed.
8/ "Verticale buitenzonwering" not tested (not available to me).

Guess this version can be released...

**Comment by totalimmersion** [comment]
Thanks a lot for you help Peter, I will submit the app to Athom.
