### ISSUE TITLE
Feature request: support for somfy protect

### ISSUE THREAD

**Issue by phatenl** [totalimmersion/com.somfy.tahoma#31]
Tahoma integrates somfy protect products like the security camera and the alarm. Would be nice to have them integrated.

**Comment by totalimmersion** [comment]
Ik ga kijken of dit in een toekomstige versie toegevoegd kan worden, maar dit zal niet zo eenvoudig zijn als de andere apparaten zoals rolluiken e.d. Ik kan dus niets garanderen.
