### ISSUE TITLE
commando open rolluiken vindt de somfy rts motoren niet meer sinds de update 

### ISSUE THREAD

**Issue by leroyneels** [totalimmersion/com.somfy.tahoma#32]
Hey Lennart ik weet niet of je app er iets mee heeft te maken maar sinds de update van gisteren ben ik niet meer in staat mijn rolluiken open te sturen door middel van een spraak commando. ik heb er al een apparte flow voor aangemaakt dat werkt, maar homey blijft me zeggen dat hij de rolluiken niet kan vinden, omdat het normaal gezien en standaar commando is. Hopelijk weet jij een oplossing. alvast bedankt. met vriendelijke groet Leroy

**Comment by totalimmersion** [comment]
Hoi Leroy,

RTS motoren worden niet door de tahoma app ondersteund. Waarschijnlijk gebruik je een andere app hiervoor.

Groet,

Lennart
