### ISSUE TITLE
Homey accepteerd hem niet

### ISSUE THREAD

**Issue by roody1997** [totalimmersion/com.somfy.tahoma#33]
net de 1.5 ge updrade, ik kan de (nieuwe buiten velux IO) rolluiken ed zien maar bij het importeren, komen ze niet in de home app 

ook een eerdere zonwering die ik had verwijdert uit homey, kan ik wel selecteren, maar krijg ik niet meer in de homey app Homey Firmware Versie: 1.5.13

de apparaten die in de homey app nog staan werken wel..

Gr Roody

**Comment by totalimmersion** [comment]
Hoi Roody,

Versie 1.5.0 van de Tahoma app is enkel compatible met Homey V2. Mocht het met Homey V2 niet werken, dan hoor ik het graag.

Groet,

Lennart
