### ISSUE TITLE
Kan geen nieuwe devices toevoegen 

### ISSUE THREAD

**Issue by woutf** [totalimmersion/com.somfy.tahoma#35]
Hi

Ik probeer mijn IO zonwering toe te voegen aan Homey. Het installeren en openen van de app werkt, maar als ik vervolgens op Exterior Vertical Blind tik, krijg ik de volgende error 'on_pair_login_failure'

**Comment by totalimmersion** [comment]
Hi, ben je wel ingelogd in de app?

**Comment by woutf** [comment]
Je bedoelt de Tahoma-app? Daar zit het probleem dan denk ik. Ik heb een Somfy Connexoon box, niet de Tahoma. Werkt met eenzelfde soort Somfy account en de Tahoma IFTTT-integragie werkt bijvoorbeeld ook. Maar deze app dan niet gok ik

**Comment by totalimmersion** [comment]
Ja in Homey onder 'instellingen', moet je bij de Tahoma app inloggen met je somfy account. Zonder dat kunnen de apparaten niet aangestuurd worden. Ik heb zelf geen Connexoon box, maar heb van meerdere mensen gehoord dat het ook met een Connexoon werkt. Ik kan daar alleen geen support op leveren, omdat ik, zoals gezegd, niet in het bezit ben van een Connexoon.

**Comment by luckyluc7** [comment]
Ik heb hetzelfde probleem, met mijn Connexoon inloggegevens kan ik niet inloggen in de Somfy Tahoma koppeling in Homey; Inloggen niet gelukt, bad credentials. Wat kan ik hier aan doen? Nieuw account aanmaken lukt niet want dan moet ik de pin invoeren van de Connexoon en die is al ingebruik..
