### ISSUE TITLE
Somfy aan sturing via IO Tahoma veranderd status niet

### ISSUE THREAD

**Issue by Hema40** [totalimmersion/com.somfy.tahoma#38]

**Comment by Hema40** [comment]
Ik heb een probleem met het besturen van mij rolluiken,
Kun jij mij helpen met een probleem waar ik vanaf de laatste update van Tahoma tegen aan loop. 
Ik zal het uitleggen na de firmware update van mij Homey heb ik problemen met de aansturing van de rolluiken welke via de Tahoma box worden aangestuurd. 
Ik heb alle apparaten in Homey verwijderd en opnieuw op Homey geïnstalleerd. 
Het zag er direct een stuk beter uit en een aantal functionaliteiten had ik daarna weer terug. ziet er prima uit. 
Echter er zit een probleempje in de aansturing waarvan ik het vermoeden heb dat het een bug is ???? 
Ik kan de rolluiken voor een deel via een flow's besturen.
Als ik de rolluiken door Homey laat sluiten gaat alles goed, echter als ik deze dan weer via een tweede Flow wil openen gaat het fout. 
Het commando open wordt niet uitgevoerd. 
Ik heb het vermoeden dat het commando niet door Homey wordt gegeven. 
Deze conclusie trek ik omdat ik via de Tahoma-box heb gezien dat de rolluiken de status gesloten hebben en dat ik de rolluiken via de Tahoma box wel kan openen.
Daar zit dan ook het verschil in in vergelijking met de status in de Homey App.
Wanneer ik de status check zie ik dat het rolluik in de grafisch weergave aangeeft dat hij gesloten is enkel als ik dan naar de pijltjes status kijk dan blijft deze wit omhoog branden. 
Naar mij idee moet het pijltje meer veranderen van omhoog wijzend in naar beneden wijzend.
Als aanvulling wil ik meegeven dat als ik de pijl handmatig naar de status gesloten (beneden wijzend) toe zet de rolluiken het commando openen wel overnemen. 
Dat is niet echt handig om elke dag op deze manier uit te voeren. 
Ik zal voor de duidelijkheid een aantal screenshots bijvoegen en hopelijk kunt u mij snel van en voorzien zijn voorzien. 
Mochten er nog vragen van onduidelijkheden zijn dan hoor ik het graag.

![tahoma versie](https://user-images.githubusercontent.com/47194535/52184625-092f5800-2816-11e9-89f8-d2cdb96c0e15.jpg)
![status gesloten beeld](https://user-images.githubusercontent.com/47194535/52184626-09c7ee80-2816-11e9-89c8-9bf8a3f9b032.jpg)
![status open beeld](https://user-images.githubusercontent.com/47194535/52184627-09c7ee80-2816-11e9-8c48-53ca7dfce381.jpg)
![status gesloten functie](https://user-images.githubusercontent.com/47194535/52184628-09c7ee80-2816-11e9-894a-4183bc3c778c.jpg)
![status open functie](https://user-images.githubusercontent.com/47194535/52184629-09c7ee80-2816-11e9-9d54-8363d24723fa.jpg)

**Comment by totalimmersion** [comment]
Hoi, ik ga er naar kijken. Hopelijk kan ik achterhalen wat er fout gaat.

**Comment by Hema40** [comment]
Lennart bedankt voor het achter haken van het probleem mbt automatisch openen het werkt weer uit de kunst
