### ISSUE TITLE
somfy tahoma error: on pair login failure

### ISSUE THREAD

**Issue by Wimdes** [totalimmersion/com.somfy.tahoma#39]

**Comment by Wimdes** [comment]
I've installed homey 2, installed the somfy tahoma ap (on my phone and in the homey app) and i have a tahoma box with 2 working outside sun screens. But wheni try to install the screens in the homey app, after a while i always get:  Unknown error: [on_pair_login_failure] 
Does anybody know a solution?

**Comment by totalimmersion** [comment]
You should login with your tahoma credentials in order to the screens in the app.

**Comment by Wimdes** [comment]
Found it. Thanks
