### ISSUE TITLE
SDK2 update - Thermis no longer working

### ISSUE THREAD

**Issue by PeterEIER** [totalimmersion/com.somfy.tahoma#5]
Seems to me that the SDK2 update broke Thermis, since the update my Thermis reading is stuck at 13.5 degC. (via the Tahoma interface I do get the correct reading).

**Comment by totalimmersion** [comment]
Hi Peter, it seems that I made a copy / pasting mistake when I was refactoring the app to SDK2. Didn't notice it, because I don't have the Thermis and therefore can't test it. I've just fixed it and will submit an update to Athom right away.

Best,

Lennart

**Comment by PeterEIER** [comment]
it's no problem for me to test any future beta version, sent me a PM when I can help you with testing / making sure you did not break the sensors you do not have.

**Comment by totalimmersion** [comment]
Thanks Peter, I will do that in the future. 1.2.1 is now available in the Athom app store, which should fix the Thermis.
