### ISSUE TITLE
SDK2 update - unable to access the app its settings/setup page

### ISSUE THREAD

**Issue by PeterEIER** [totalimmersion/com.somfy.tahoma#6]
App's (v1.2.0) settings page shows a circling "thing" forever, downloaded v1.2.1 from GitHub same issue.

Notes: 
- Tahoma scenario's can be selected with v1.2.1 (which was not the case with v1.2.0).
- Thermis is working again with v1.2.1
- since the update to v1.2.0 flows that make use of Sunis do not trigger anymore, have to wait till sunrise to see if v1.2.1 fixes that issue.

**Comment by totalimmersion** [comment]
Both the settings page and the triggers should now be working again on 1.2.1 (which is now available in the Athom app store).

**Comment by PeterEIER** [comment]
App settings / config page is working again (v1.2.1). Will report on Sunis triggered flows tomorrow.

**Comment by PeterEIER** [comment]
Flows triggered by Sunis are working again (v1.2.1). Issues solved !
