### ISSUE TITLE
Geen verbinding meer met rolluik en opnieuw aanmelden van de app wil niet

### ISSUE THREAD

**Issue by RNijhof** [totalimmersion/com.somfy.tahoma#67]
Sinds een aantal dagen werkt de aansturing via homey niet meer in combinatie met de app. Via de tahoma omgeving werkt het wel, dus opnieuw de app in homey geinstalleerd, maar de inloggegevens werken niet meer ondanks dit lokaal wel werkt.

**Comment by cento007** [comment]
Hi,

Het lijkt nog niet hier mee te maken hoop ik:

Beste Somfy TaHoma/Connexoon gebruiker,
Volgens onze gegevens heb je in de afgelopen 3 maanden een verouderde methode gebruikt om in te loggen op je Somfy TaHoma/Somfy Connexoon. 

Hierbij informeren wij je dat, in verband met de veiligheid, onze systemen bijgewerkt worden op 3 december 2019, waarna inloggen niet meer mogelijk is via onderstaande methodes: 

Een oude Somfy App (versie voor 2018) of een verouderd toestel (iPhone 4 of ouder, iPad 1 of Android 4.0 of ouder). Wij adviseren je om de Somfy app te updaten of een nieuwer toestel te gebruiken. 
**Applicaties van derde partijen: Home Assistant, Mediola of Jeedom. Wij adviseren je de applicatie te updaten zodat je onze nieuwe API gebruikt – voor meer informatie bezoek de desbetreffende partner website.** 
 Met vriendelijke groet, 

 Somfy

**Comment by RNijhof** [comment]
Uiteindelijk bleek het te liggen aan bepaalde wegen niet werkte, terwijl deze wel zouden moeten werken. Na het resetten van het één en ander (bij somfy) werkt momenteel alles weer.
