### ISSUE TITLE
Tahoma Rolluiken bedienen

### ISSUE THREAD

**Issue by Divemasters** [totalimmersion/com.somfy.tahoma#7]
Beste Lennart,

Ik heb moeite om je app aan de gang te krijgen, Installatie en inloggen gaat goed maar kan vervolgens geen rolluiken vinden/toevoegen. Wat heb je nodig om uit te zoeken wat ik verkeerd doe of wat er verkeerd gaat? 

Vriendelijke groeten,

Ruud Kort

**Comment by totalimmersion** [comment]
Hoi Ruud,

Sorry voor de late reactie. Ontwikkeling van de app heeft een paar maanden stil gelegen. Ik heb een document gemaakt met instructies voor het aanleveren van de juiste informatie (bijgevoegd bij dit comment). Als je dit wilt doen en de informatie wilt toevoegen aan dit issue, dan zal ik proberen om de apparaten aan de app toe te voegen.

Groet,

Lennart
[Instructions for the TaHoma devices.pdf](https://github.com/totalimmersion/com.somfy.tahoma/files/1815899/Instructions.for.the.TaHoma.devices.pdf)

**Comment by totalimmersion** [comment]
Issue gesloten vanwege geen reactie.
