### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by tkroon89** [totalimmersion/com.somfy.tahoma#84]
The app has stopped working on Homey. It fails to login, due to an expired certificate. Please help!

**Comment by jvdweijden** [comment]
I've got the same issue. 
Removing and (re)installing the app did not solve the issue. Devices are not controlable anymore.

![Screenshot_20200531-093211_Homey](https://user-images.githubusercontent.com/46780573/83347539-fc494880-a325-11ea-93fb-64d07545344b.jpg)

**Comment by RD1951** [comment]
Hi.... I have exactly the same issue as described.... No solution or workaround... 
The certificate expired and was wondering whether the developer of the APP (that normally works fine)   can help and find a solution.....

Thanks in advance   regards....

**Comment by tkroon89** [comment]
Updating Homey to 4.2.0 fixed the problem!
